### ISSUE TITLE
Reference or Pin Diagram of Arduino Pinouts for XMC

### ISSUE THREAD

**Issue by sharmashubha** [techpaul/XMC-for-Arduino#6]
Can you please share a pin diagram or any reference of how are arduino pins numbered from 0-33 as mentioned in XMC1300 wiki?? @techpaul

**Comment by techpaul** [comment]
The text diagram on https://github.com/techpaul/XMC-for-Arduino/wiki/Hardware-Pins---Pinout-XMC1300-Boot-Kit  Shows the pins in order of the pins on the board

When I get some time (maybe during lockdown), I need to get some pictures sorted

The wiki page shows the pins in order they are on the board and below that in Arduino pin order

**Comment by sharmashubha** [comment]
yes. I need to know that arduino pin order. If you can get some time, please share some pictures. As I can see in the pin_config.h file, all the ADC pins are marked as: A0 is 0, A1 is 1, A2 is 2 and so on..But Infineon's official wiki page has them marked as different pins.
I am attaching screenshots:
1. Pinout diagram of xmc1100 boot kit
2. Config.h file for pins

We see that SS, MOSI, MISO, SCK are maked correctly as 10,11,12,13 in code and in diagram but for 
A0, A1, A2.. they are 17,18,19... but 0,1,2.. in code. So I asked you for a reference arduino pin diagram based on which these are numbered. When ever you have time, please share your understanding on this. Thanks for you reply.
<img width="399" alt="configpinout_code screenshot" src="https://user-images.githubusercontent.com/59479043/77417385-912f4300-6dc5-11ea-94a7-5cc67f16a723.PNG">
<img width="609" alt="pinout diagram_xmc1100 bootkit" src="https://user-images.githubusercontent.com/59479043/77417386-92607000-6dc5-11ea-8ba8-c995212fa014.PNG">

**Comment by techpaul** [comment]
XMC1100 and XMC1300 are **DIFFERENT** boards

Analog pins on every board I have seen (even Arduinos) are at best labelled on the board as A0...An

These happen to translate to 0...n for analogRead functions

The config.h file for XMC1300 is under board variants for XMC1300 and is CORRECT and I know it works as I have several projects using it, with pins referred to in code as A0...An

They are labelled in that table as A0..An

**Comment by sharmashubha** [comment]
okay. Well thanks. I was wondering that SPI pins are same in code and pinout diagram but how does it work when its different in code and pinout diagram for analog input pins. Don't you feel that it should be consistent  in code and diagram both. But anyways thankyou for your input. I appreciate it !

**Comment by techpaul** [comment]
THE boiards are **DIFFERENT** physically in shape, size and pin locations.

All pins that are labelled **the same** DO WORK CORRECTLY, when you use the pins as labelled

If you are using a XMC1100 use that pinout diagram

If you are using a XMC1300 use the table from the wiki

It is like having a car and some have the petrol cap on the left some on the right, as long as you open the petrol cap you still fill the petrol tank, no matter what side the petrol cap is located.

**Comment by techpaul** [comment]
Please also note 

XMC1100 Boot Kit has 31 Arduino pins
XMC1100 2G0 has 16 Arduino pins
XMC1300 boot Kit has 34 Arduino pins

Any pin numbers being same between boards is PURE COINCIDENCE or CHANCE

Use the pin numbers for the board you are using.

Those that are labelled the same between boards work the same
